package edu.augustana.csc305.project.userInterface;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;

/**
 * An abstract base class for all views (screens) in the application.
 * <p>
 * This class also serves as a central repository for application-wide UI constants
 * and static helper methods for creating consistent UI components.
 * </p>
 * Styles generated by Gemini 2.5 Pro.
 * Helper methods added by Gemini 2.5 Pro to centralize styling.
 */
public abstract class View extends VBox {

    public static final String BG_COLOR = "#2c3e50";         // Dark Blue-Gray (Main Background)
    public static final String PANE_BG_COLOR = "#34495e";    // Medium Blue-Gray (Content/Pane Background)
    public static final String NODE_BG_COLOR = "#2c3e50";    // Dark Blue-Gray (Match Node Background)
    public static final String BORDER_COLOR = "#7f8c8d";     // Gray (Default Border)
    public static final String TEXT_COLOR = "#ecf0f1";       // Off-White (Primary Text)
    public static final String ACCENT_COLOR = "#1abc9c";     // Turquoise/Teal (Primary Highlight/Winner)
    public static final String LINE_COLOR = "#95a5a6";       // Medium Gray (Connector Lines)
    public static final String HOVER_BG_COLOR = "#3b5066";   // Slightly lighter for hover effect
    public static final String LIST_CELL_ALT_BG_COLOR = "#4a6278";
    public static final String WARNING_COLOR_BASE = "#c0392b"; // Dark Red
    public static final String WARNING_COLOR_HOVER = "#e74c3c"; // Bright Red
    public static final String TABLE_CELL_TEXT_COLOR = "#ecf0f1"; // Off-White (Primary Text for tables)

    public static final double MAX_SCALE = 2.5;
    public static final double MIN_SCALE = 0.25;
    /**
     * Style string for a winning team/highlighted text.
     */
    public static final String WINNER_STYLE = "-fx-font-weight: bold; -fx-text-fill: " + ACCENT_COLOR + ";";
    /**
     * Style string for normal text.
     */
    public static final String NORMAL_STYLE = "-fx-font-weight: normal; -fx-text-fill: " + TEXT_COLOR + ";";

    /**
     * Base style for navigation buttons (dark theme).
     */
    public static final String BUTTON_STYLE =
            "-fx-background-color: " + PANE_BG_COLOR + ";" +
                    "-fx-text-fill: " + TEXT_COLOR + ";" +
                    "-fx-font-weight: bold;" +
                    "-fx-border-color: " + BORDER_COLOR + ";" +
                    "-fx-border-radius: 5;";
    /**
     * Hover style for navigation buttons.
     */
    public static final String BUTTON_HOVER_STYLE =
            "-fx-background-color: #4a6278;" +
                    "-fx-text-fill: " + TEXT_COLOR + ";" +
                    "-fx-font-weight: bold;" +
                    "-fx-border-color: " + BORDER_COLOR + ";" +
                    "-fx-border-radius: 5;";

    /**
     * Base style for warning/delete buttons.
     */
    public static final String BUTTON_WARNING_STYLE =
            BUTTON_STYLE.replace(PANE_BG_COLOR, WARNING_COLOR_BASE);

    /**
     * Hover style for warning/delete buttons.
     */
    public static final String BUTTON_WARNING_HOVER_STYLE =
            BUTTON_HOVER_STYLE.replace("#4a6278", WARNING_COLOR_HOVER);


    private static final String SHADOW_COLOR_40 = "#00000066";
    /**
     * Base style for a match node (dark theme).
     * FIX: Replaced rgba(...) with robust 8-digit hex for -fx-effect color.
     */
    public static final String DEFAULT_MATCH_STYLE =
            "-fx-background-color: " + NODE_BG_COLOR + ";" +
                    "-fx-border-color: " + BORDER_COLOR + ";" +
                    "-fx-border-radius: 8;" +
                    "-fx-background-radius: 8;" +
                    "-fx-effect: dropshadow(gaussian, " + SHADOW_COLOR_40 + ", 10, 0.5, 0, 0);";
    private static final String SHADOW_COLOR_60 = "#00000099";
    /**
     * Hover style for an interactive match node.
     * FIX: Replaced rgba(...) with robust 8-digit hex for -fx-effect color.
     */
    public static final String HOVER_MATCH_STYLE =
            "-fx-background-color: " + HOVER_BG_COLOR + ";" +
                    "-fx-border-color: " + ACCENT_COLOR + ";" +
                    "-fx-border-width: 2;" +
                    "-fx-border-radius: 8;" +
                    "-fx-background-radius: 8;" +
                    "-fx-effect: dropshadow(gaussian, " + SHADOW_COLOR_60 + ", 15, 0.7, 0, 0);";

    /**
     * Base style for text fields and password fields.
     */
    public static final String TEXT_INPUT_STYLE =
            "-fx-background-color: " + NODE_BG_COLOR + ";" +
                    "-fx-text-fill: " + TEXT_COLOR + ";" +
                    "-fx-border-color: " + BORDER_COLOR + ";" +
                    "-fx-border-radius: 5;" +
                    "-fx-background-radius: 5;" +
                    "-fx-prompt-text-fill: " + LINE_COLOR + ";";

    /**
     * Base style for list views.
     */
    public static final String LIST_VIEW_STYLE =
            "-fx-background-color: " + PANE_BG_COLOR + ";" +
                    "-fx-border-color: " + BORDER_COLOR + ";" +
                    "-fx-control-inner-background: " + PANE_BG_COLOR + ";";

    /**
     * Base style for table views.
     * UPDATED: Added styles for headers and column/cell borders.
     */
    public static final String TABLE_VIEW_STYLE =
            // --- General Table Styling ---
            "-fx-background-color: " + PANE_BG_COLOR + ";" +
                    "-fx-control-inner-background: " + PANE_BG_COLOR + ";" +
                    "-fx-table-cell-border-color: " + BORDER_COLOR + ";" +
                    "-fx-background-insets: 0;" +
                    "-fx-padding: 0;" +

                    // --- Header Row Background ---
                    ".table-view .column-header-background {" +
                    "  -fx-background-color: " + NODE_BG_COLOR + ";" +
                    "  -fx-border-color: " + BORDER_COLOR + ";" +
                    "  -fx-border-width: 0 0 1 0;" +
                    "}" +

                    // --- Header Row Empty Space (Filler) ---
                    ".table-view .filler {" +
                    "  -fx-background-color: " + NODE_BG_COLOR + ";" +
                    "}" +

                    // --- Individual Header Column ---
                    ".table-view .column-header {" +
                    "  -fx-background-color: transparent;" +
                    "  -fx-border-color: " + BORDER_COLOR + ";" +
                    "  -fx-border-width: 0 1 0 0;" +
                    "  -fx-padding: 8px;" +
                    "}" +

                    // --- Header Text Label ---
                    ".table-view .column-header .label {" +
                    "  -fx-text-fill: " + TEXT_COLOR + ";" +
                    "  -fx-font-weight: bold;" +
                    "  -fx-padding: 0 0 0 5px;" +
                    "}";


    /**
     * Creates a new base {@code View}.
     * <p>
     * Subclasses should build their UI components in their constructor.
     * </p>
     */
    public View() {
    }

    /**
     * Refreshes the view so its contents reflect the current state
     * of the application's model.
     * <p>
     * This method is called whenever the controller determines
     * that the UI needs to be updated.
     * </p>
     */
    public abstract void refreshView();

    /**
     * Applies the standard button styling and hover effects to a button.
     *
     * @param button The button to style.
     */
    public static void styleButton(Button button) {
        styleButton(button, false);
    }

    /**
     * Applies consistent styling and hover effects to a button, with an
     * option for a warning/danger style (e.g., for "Delete" or "Logout").
     *
     * @param button          The button to style.
     * @param isWarningButton If true, applies a red warning color scheme.
     */
    public static void styleButton(Button button, boolean isWarningButton) {
        String baseStyle = isWarningButton ? BUTTON_WARNING_STYLE : BUTTON_STYLE;
        String hoverStyle = isWarningButton ? BUTTON_WARNING_HOVER_STYLE : BUTTON_HOVER_STYLE;

        button.setStyle(baseStyle);
        button.setOnMouseEntered(e -> button.setStyle(hoverStyle));
        button.setOnMouseExited(e -> button.setStyle(baseStyle));
    }

    /**
     * Applies consistent styling to a TextField.
     *
     * @param field The text field to style.
     */
    public static void styleTextField(TextField field) {
        field.setStyle(TEXT_INPUT_STYLE);
    }

    /**
     * Applies consistent styling to a PasswordField.
     *
     * @param field The password field to style.
     */
    public static void stylePasswordField(PasswordField field) {
        field.setStyle(TEXT_INPUT_STYLE);
    }

    /**
     * Applies consistent styling to a ComboBox.
     * This styles the button part to match other buttons.
     *
     * @param comboBox The combo box to style.
     */
    public static void styleComboBox(ComboBox<?> comboBox) {
        comboBox.setStyle(BUTTON_STYLE);
    }

    /**
     * Applies consistent styling to a CheckBox.
     *
     * @param checkBox The check box to style.
     */
    public static void styleCheckBox(CheckBox checkBox) {
        checkBox.setStyle("-fx-text-fill: " + TEXT_COLOR + "; -fx-font-weight: bold;");
    }

    /**
     * Applies consistent styling to a ListView.
     *
     * @param listView The list view to style.
     */
    public static void styleListView(ListView<?> listView) {
        listView.setStyle(LIST_VIEW_STYLE);
    }

    /**
     * Applies consistent styling to a TableView.
     *
     * @param tableView The table view to style.
     */
    public static void styleTableView(TableView<?> tableView) {
        tableView.setStyle(TABLE_VIEW_STYLE);
    }

    /**
     * Creates a styled VBox container for a section of the UI with a title.
     *
     * @param title The text to display as the section header.
     * @return A styled VBox configured as a section container with a title.
     */
    public static VBox createSectionBox(String title) {
        VBox box = new VBox(10);
        box.setPadding(new Insets(15));
        box.setStyle("-fx-background-color: " + PANE_BG_COLOR + "; -fx-background-radius: 8;");
        box.setAlignment(Pos.TOP_CENTER);

        if (title != null && !title.isEmpty()) {
            Label label = createStyledLabel(title, TEXT_COLOR, 16, true);
            box.getChildren().add(label);
        }

        box.setMinWidth(400);
        box.setAlignment(Pos.CENTER);

        return box;
    }

    /**
     * Creates a styled label with the specified text, color, size, and weight.
     *
     * @param text   The text of the label.
     * @param color  The text color (in CSS format, e.g., "#ecf0f1").
     * @param size   The font size.
     * @param isBold True if the font should be bold, false for normal.
     * @return A fully styled Label.
     */
    public static Label createStyledLabel(String text, String color, int size, boolean isBold) {
        Label label = new Label(text);
        label.setFont(Font.font("System", isBold ? FontWeight.BOLD : FontWeight.NORMAL, size));
        label.setStyle("-fx-text-fill: " + color + ";");
        return label;
    }

    /**
     * Creates a styled label with the default text color.
     *
     * @param text   The text of the label.
     * @param size   The font size.
     * @param isBold True if the font should be bold, false for normal.
     * @return A fully styled Label.
     */
    public static Label createStyledLabel(String text, int size, boolean isBold) {
        return createStyledLabel(text, TEXT_COLOR, size, isBold);
    }
}